---
ohmyzsh_case_sensitive: false
ohmyzsh_hyphen_insensitive: false
ohmyzsh_disable_update_prompt: false
ohmyzsh_disable_auto_update: false
ohmyzsh_update_days: 13
ohmyzsh_disable_ls_colors: false
ohmyzsh_disable_auto_title: false
ohmyzsh_disable_correction: false
ohmyzsh_completion_waiting_dots: true
ohmyzsh_disable_untracked_files_dirty: false
ohmyzsh_custom: "$ZSH/custom"
ohmyzsh_plugins: "git zsh-history-substring-search zsh-autosuggestions"
ohmyzsh_nvm: false
ohmyzsh_gpg: false

