---
- name: Mac Setup Playbook
  hosts: all

  vars_files:
    - vars/vscode.yml
    - vars/homebrew.yml
    - vars/mas.yml
    - vars/dock.yml

  # List extra variables, if necessary
  # vars:

  # List additional tasks, if necessary
  # tasks:

  roles:
    - homebrew
    - dotfiles
    - vscode
    - mas
    - dock
    - ohmyzsh
