---
- name: Mac Setup Playbook
  hosts: all

- vars_files:
- vars/mas.yml
- vars/homebrew.yml
- vars/dock.yml
- vars/ohmyzsh.yml
- vars/gitconfig.yml

# List extra variables, if necessary
# vars:

# List additional tasks, if necessary
# tasks:

roles:
- { role: geerlingguy.mac.homebrew }
- { role: geerlingguy.mac.mas }
- { role: geerlingguy.mac.dock }
- { role: geerlingguy.dotfiles }
- ohmyzsh
