---
- name: Mac Setup Playbook
  hosts: all

  vars_files:
    - vars/vscode.yml
    - vars/mas.yml
    - vars/homebrew.yml
    - vars/dotfiles.yml
    - vars/dock.yml

  # List extra variables, if necessary
  # vars:

  # List additional tasks, if necessary
  # tasks:

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock
    - geerlingguy.dotfiles
    - vscode
    - ohmyzsh
    - terminal
