---
- name: Get latest Fira Code Font Release
  uri:
    url: 'https://api.github.com/repos/tonsky/FiraCode/releases/latest'
    return_content: true
    validate_certs: false
  register: fira_code

- name: Install Fira Code Font {{ fira_code.json.tag_name }}
  unarchive:
    src:
      'https://github.com/tonsky/FiraCode/releases/download/{{
      fira_code.json.tag_name }}/Fira_Code_v{{ fira_code.json.tag_name }}.zip'
    dest: '~/Library/Fonts'
    remote_src: true
    keep_newer: true
    validate_certs: false

- name: Install spaceship-prompt
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt

- name: Configure spaceship-prompt
  file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link